AWSTemplateFormatVersion: 2010-09-09

Description: Create S3 Bucket with Static Website Hosting and Public Access

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: 'index.html'
        ErrorDocument: 'error.html'
        
  Bucketpolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Sid: PublicAccess
            Effect: Allow
            Principal: '*'
            Action:
              - "s3:GetObject"
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}/*"

Outputs:
  WebsiteEndPoint:
    Description: 'URL to access static website direct to S3'
    Value: !GetAtt S3Bucket.WebsiteURL