apiVersion: v1
kind: Pod
metadata: 
  name: ubuntu-container
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu-container
    ports:
    - containerPort: 8080
    command:
    - sleep
    - 1500
  initContainers:
  - name: init-myservice
    image: busybox
    command: 
    - sh 
    - -c
    - until nslookup google.com; done;
