- name: "Schedule backups"
  ansible.builtin.cron:
    name: "Backup /var folder every Friday at 2am"
    weekday: "5"
    minute: "0"
    hour: "2"
    user: "root"
    job: "tar -czf /tmp/var-{{ ansible_hostname }}.tgz /var"
    cron_file: var_folder
