---
apiVersion: v1
kind: ConfigMap
metadata:
  name:pod-config
data:
  APP_COLOR: blue
  APP_MODE: prod

---
apiVersion: v1
kind: Pod
metadata: 
  name: ubuntu-pod
spec:
  containers:
    - name: ubuntu-pod
      image: ubuntu
      ports:
        - containerPort: 8080
      envFrom:
        - configMapKeyref:
            name: pod-config
